package net.weltontep.morebountifulstones.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.Blocks;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.weltontep.morebountifulstones.MoreBountifulStones;
import net.weltontep.morebountifulstones.block.ModBlocks;

public class ModItemGroups {
    public static final ItemGroup MORE_BOUNTIFUL_STONES_ITEM_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(MoreBountifulStones.MOD_ID, "more_bountiful_stones"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ModBlocks.ANDESITE_COBBLED))
                    .displayName(Text.translatable("itemgroup.morebountifulstones.more_bountiful_stones"))
                    .entries((displayContext, entries) -> {
                        entries.add(ModBlocks.ANDESITE_COBBLED);
                        entries.add(ModBlocks.ANDESITE_COBBLED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_COBBLED_SLAB);
                        entries.add(ModBlocks.ANDESITE_COBBLED_WALL);
                        entries.add(Blocks.ANDESITE);
                        entries.add(Blocks.ANDESITE_SLAB);
                        entries.add(Blocks.ANDESITE_STAIRS);
                        entries.add(Blocks.ANDESITE_WALL);
                        entries.add(Blocks.POLISHED_ANDESITE);
                        entries.add(Blocks.POLISHED_ANDESITE_STAIRS);
                        entries.add(Blocks.POLISHED_ANDESITE_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_BUTTON);
                        entries.add(ModBlocks.ANDESITE_POLISHED_PRESSURE_PLATE);
                        entries.add(ModBlocks.ANDESITE_SMOOTH);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_STAIRS);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_SLAB);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_WALL);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_CRACKED);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_SMOOTH_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICKS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICKS_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_LARGE_BRICK_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICKS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICKS_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SQUARE_BRICK_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILES);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILES_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_TILE_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SHINGLES);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SHINGLE_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SHINGLE_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_SHINGLE_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_CIRCULAR_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_DENT_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CARVED_MOSAIC_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICKS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICKS_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICKS_BRAIDED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_BRAIDED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_BRAIDED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_BRAIDED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICKS_PINWHEEL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_PINWHEEL_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_PINWHEEL_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_PINWHEEL_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICKS_ROAD);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_ROAD_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_ROAD_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_BRICK_ROAD_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANKS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANKS_CRACKED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_CRACKED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_CRACKED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_CRACKED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PLANK_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILES);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILES_CHECKERED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_CHECKERED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_CHECKERED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_CHECKERED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CUT_TILE_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_PILLAR);
                        entries.add(ModBlocks.ANDESITE_POLISHED_PILLAR_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_PILLAR_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_PILLAR_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_TWISTED);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_TWISTED_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_TWISTED_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_TWISTED_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_GREEK);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_GREEK_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_GREEK_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_GREEK_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_ORNATE);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_ORNATE_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_ORNATE_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_ORNATE_WALL);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_PYRAMID);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_PYRAMID_STAIRS);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_PYRAMID_SLAB);
                        entries.add(ModBlocks.ANDESITE_POLISHED_CHISELED_PYRAMID_WALL);
                    })

                    .build());

    public static void registerItemGroups() {
        MoreBountifulStones.LOGGER.info("Registering Item Groups for " + MoreBountifulStones.MOD_ID);
    }
}
